# Tool settings
username: ajaxtartaglia
steam_path: "C:/Program Files (x86)/Steam"
# rollback_path: "src/util/steam_rollback_tool"
# rollback_exe_path: "src/util/steam_rollback_tool/steam-rollback.exe"

# Github urls
# steam_rollback_url: https://github.com/IMXNOOBX/steam-rollback/releases/download/steam-rollback/steam-rollback.exe

# Steam 클라이언트 다운그레이드 설정
downgrade_manifest_id: 1685488080         # 목표 구형 클라이언트 버전 (2023년 5월 31일 빌드)
downgrade_wayback_date: 20230531113527    # 해당 Wayback Machine 날짜