# Tool settings
username: ajaxtartaglia
# steam_path: "C:/Program Files (x86)/Steam" # <-- 이 줄을 추가하고 당신의 실제 Steam 설치 경로로 변경하세요!
rollback_path: "src/util/steam_rollback_tool" # <-- 이 줄을 수정합니다.
rollback_exe_path: "src/util/steam_rollback_tool/steam-rollback.exe" # <-- 이 줄도 수정합니다.

# Github urls
github_url: https://github.com/kWAYTV/steam-ssfn-logger
version_github_url: https://raw.githubusercontent.com/kWAYTV/steam-ssfn-logger/main/src/helper/config.py
steam_rollback_url: https://github.com/IMXNOOBX/steam-rollback/releases/download/steam-rollback/steam-rollback.exe